name: textile
version: 0.1.0

description: A portable interpreter of Textile Markup Language into HTML written in dart language.
author: Omkar Todkar <omtodkar@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  charcode: ^1.1.0

dev_dependencies:
  pedantic: ^1.4.0
  test: ^1.6.2
